# Shell plugins

[".config/zsh/plugins/powerlevel10k"]
type = "archive"
url = "https://github.com/romkatv/powerlevel10k/archive/refs/tags/v1.19.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-autosuggestions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/tags/v0.7.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-completions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-completions/archive/refs/tags/0.35.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/tags/0.8.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-vim-mode"]
type = "archive"
url = "https://github.com/softmoth/zsh-vim-mode/archive/1f9953b.tar.gz"
exact = true
stripcomponents = 1

[".config/bash/plugins/bash-preexec"]
type = "archive"
url = "https://github.com/rcaloras/bash-preexec/archive/refs/tags/0.5.0.tar.gz"
exact = true
stripcomponents = 1

# CLI Theming

[".config/btop/themes/onedark.theme"]
type = "file"
url = "https://raw.githubusercontent.com/aristocratos/btop/v1.2.13/themes/onedark.theme"

# KDE Plasma Theming

[".local/share/aurorae/themes/ActiveAccentFrame/"]
type = "archive"
url = "https://github.com/nclarius/Plasma-window-decorations/archive/refs/tags/v9.2.tar.gz"
exact = true
stripcomponents = 2
include = ["*/ActiveAccentFrame/*"]
