# Shell plugins

[".config/bash/plugins/bash-preexec"]
type = "archive"
url = "https://github.com/rcaloras/bash-preexec/archive/refs/tags/0.5.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/powerlevel10k"]
type = "archive"
url = "https://github.com/romkatv/powerlevel10k/archive/refs/tags/v1.20.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-autosuggestions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/tags/v0.7.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-completions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-completions/archive/refs/tags/0.35.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/tags/0.8.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-vim-mode"]
type = "archive"
url = "https://github.com/softmoth/zsh-vim-mode/archive/1f9953b.tar.gz"
exact = true
stripcomponents = 1

# Zellij plugins

[".local/share/zellij/plugins/zj-quit.wasm"]
type = "file"
url = "https://github.com/cristiand391/zj-quit/releases/download/0.3.0/zj-quit.wasm"

[".local/share/zellij/plugins/zellij-forgot.wasm"]
type = "file"
url = "https://github.com/karimould/zellij-forgot/releases/download/0.4.0/zellij_forgot.wasm"

[".local/share/zellij/plugins/zjstatus.wasm"]
type = "file"
url = "https://github.com/dj95/zjstatus/releases/download/v0.16.0/zjstatus.wasm"

# CLI Theming

[".config/btop/themes/onedark.theme"]
type = "file"
url = "https://raw.githubusercontent.com/aristocratos/btop/v1.2.13/themes/onedark.theme"

# KDE Plasma Theming

[".local/share/aurorae/themes/ActiveAccentFrame"]
type = "archive"
url = "https://github.com/nclarius/Plasma-window-decorations/archive/0205869.tar.gz"
exact = true
stripcomponents = 2
include = ["*/ActiveAccentFrame/*"]

[".local/share/color-schemes/One-Dark-Blue.colors"]
type = "file"
url = "https://raw.githubusercontent.com/Prayag2/kde_onedark/v2.1/color-schemes/One-Dark/One-Dark-Blue.colors"

[".local/share/color-schemes/One-Dark-Green.colors"]
type = "file"
url = "https://raw.githubusercontent.com/Prayag2/kde_onedark/v2.1/color-schemes/One-Dark/One-Dark-Green.colors"

[".local/share/color-schemes/One-Dark-Red.colors"]
type = "file"
url = "https://raw.githubusercontent.com/Prayag2/kde_onedark/v2.1/color-schemes/One-Dark/One-Dark-Red.colors"

[".local/share/color-schemes/One-Dark-Yellow.colors"]
type = "file"
url = "https://raw.githubusercontent.com/Prayag2/kde_onedark/v2.1/color-schemes/One-Dark/One-Dark-Yellow.colors"

[".local/share/plasma/desktoptheme/Arch"]
type = "archive"
# Note: there are no release tags, so we must pull from main
url = "https://github.com/ddh4r4m/Arch/archive/14ab5e5.tar.gz"
exact = true
include = ["*/plasma/desktoptheme/Arch/**"]
stripcomponents = 4

[".local/share/plasma/plasmoids/org.kde.panel.transparency.toggle"]
type = "archive"
url = "https://github.com/sanjay-kr-commit/panelTransparencyToggleForPlasma6/archive/refs/heads/main.zip"
exact = true
stripcomponents = 1

[".local/share/plasma/plasmoids/org.kde.plasma.ginti"]
type = "archive"
url = "https://github.com/dhruv8sh/plasma6-desktopindicator-gnome/archive/refs/tags/v0.5.tar.gz"
exact = true
stripcomponents = 1

[".local/share/plasma/plasmoids/org.kde.plasma.plasm6desktopindicator"]
type = "archive"
url = "https://github.com/dhruv8sh/plasma6-desktop-indicator/archive/refs/tags/v0.3.tar.gz"
exact = true
stripcomponents = 1

# Extra icons

[".local/share/icons/distrobox"]
type = "archive"
url = "https://github.com/89luca89/distrobox/archive/refs/tags/1.7.2.1.tar.gz"
exact = true
include = ["*/docs/assets/png/distros/**"]
stripcomponents = 5

# KWin Scripts

[".local/share/kwin/scripts/temporary-virtual-desktops"]
type = "archive"
url = "https://github.com/Ubiquitine/temporary-virtual-desktops/archive/refs/tags/v0.3.1.tar.gz"
exact = true
stripcomponents = 1

# Fonts

[".local/share/fonts/Intel One Mono"]
type = "archive"
url = "https://github.com/intel/intel-one-mono/archive/refs/heads/main.zip"
exact = true
stripcomponents = 3
include = ["*/fonts/ttf/*"]

[".local/share/fonts/Atkinson Hyperlegible"]
type = "archive"
url = "https://github.com/googlefonts/atkinson-hyperlegible/archive/refs/heads/main.zip"
exact = true
stripcomponents = 3
include = ["*/fonts/ttf/*"]

[".local/share/fonts/Intone Mono Nerd Font"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IntelOneMono.zip"
exact = true
