# Shell plugins

[".config/bash/plugins/bash-preexec"]
type = "archive"
url = "https://github.com/rcaloras/bash-preexec/archive/refs/tags/0.5.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/powerlevel10k"]
type = "archive"
url = "https://github.com/romkatv/powerlevel10k/archive/refs/tags/v1.19.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-autosuggestions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/tags/v0.7.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-completions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-completions/archive/refs/tags/0.35.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/tags/0.8.0.tar.gz"
exact = true
stripcomponents = 1

[".config/zsh/plugins/zsh-vim-mode"]
type = "archive"
url = "https://github.com/softmoth/zsh-vim-mode/archive/1f9953b.tar.gz"
exact = true
stripcomponents = 1

# CLI Theming

[".config/btop/themes/onedark.theme"]
type = "file"
url = "https://raw.githubusercontent.com/aristocratos/btop/v1.2.13/themes/onedark.theme"

# KDE Plasma Theming

[".local/share/aurorae/themes/ActiveAccentFrame"]
type = "archive"
url = "https://github.com/nclarius/Plasma-window-decorations/archive/0205869.tar.gz"
exact = true
stripcomponents = 2
include = ["*/ActiveAccentFrame/*"]

[".local/share/color-schemes/One-Dark-Blue.colors"]
type = "file"
url = "https://raw.githubusercontent.com/Prayag2/kde_onedark/v2.1/color-schemes/One-Dark/One-Dark-Blue.colors"

[".local/share/color-schemes/One-Dark-Green.colors"]
type = "file"
url = "https://raw.githubusercontent.com/Prayag2/kde_onedark/v2.1/color-schemes/One-Dark/One-Dark-Green.colors"

[".local/share/color-schemes/One-Dark-Red.colors"]
type = "file"
url = "https://raw.githubusercontent.com/Prayag2/kde_onedark/v2.1/color-schemes/One-Dark/One-Dark-Red.colors"

[".local/share/color-schemes/One-Dark-Yellow.colors"]
type = "file"
url = "https://raw.githubusercontent.com/Prayag2/kde_onedark/v2.1/color-schemes/One-Dark/One-Dark-Yellow.colors"

[".local/share/plasma/desktoptheme/Arch"]
type = "archive"
# Note: there are no release tags, so we must pull from main
url = "https://github.com/ddh4r4m/Arch/archive/14ab5e5.tar.gz"
exact = true
include = ["*/plasma/desktoptheme/Arch/**"]
stripcomponents = 4

[".local/share/plasma/plasmoids/com.github.zren.simpleweather"]
type = "archive"
url = "https://github.com/Zren/plasma-applet-simpleweather/archive/refs/tags/v8.tar.gz"
exact = true
include = ["*/package/**"]
stripcomponents = 2

[".local/share/plasma/plasmoids/org.kde.paneltransparencybutton"]
type = "archive"
url = "https://github.com/psifidotos/paneltransparencybutton/archive/refs/tags/0.2.0.tar.gz"
exact = true
stripcomponents = 1

[".local/share/plasma/plasmoids/org.kde.plasma.minimaldesktopindicator"]
type = "archive"
# Note: there are no release tags, so we must pull from main
url = "https://github.com/DualityKyle/plasma-desktop-indicator/archive/3298648.tar.gz"
exact = true
stripcomponents = 1

# KWin Scripts
[".local/share/kwin/scripts/autocomposer"]
type = "archive"
url = "https://gitlab.com/es20490446e/kwin-script-autocomposer/-/archive/5f4d617a.tar.gz"
exact = true
include = ["*/root/usr/share/kwin/scripts/autocomposer/**"]
stripcomponents = 7

[".local/share/kwin/scripts/dynamic_workspaces"]
type = "archive"
url = "https://github.com/d86leader/dynamic_workspaces/archive/refs/tags/v2.0.tar.gz"
exact = true
stripcomponents = 1

[".local/share/kwin/scripts/kwin-live-captions-assistant"]
type = "archive"
url = "https://github.com/abb128/kwin-live-captions-assistant/archive/6e403ec.tar.gz"
exact = true
stripcomponents = 1

[".local/share/kwin/scripts/restoreToScreen"]
type = "archive"
url = "https://github.com/Hegemonia123/restoreToScreen/archive/53e1b4a.tar.gz"
exact = true
stripcomponents = 1

[".local/share/kwin/scripts/stepmove"]
type = "archive"
url = "https://github.com/nclarius/KWin-window-geometry-scripts/archive/refs/tags/step-move_v3.2.tar.gz"
exact = true
include = ["*/step-move/**"]
stripcomponents = 2

[".local/share/kwin/scripts/stepregrid"]
type = "archive"
url = "https://github.com/nclarius/KWin-window-geometry-scripts/archive/refs/tags/step-regrid_v3.0.tar.gz"
exact = true
include = ["*/step-regrid/**"]
stripcomponents = 2

[".local/share/kwin/scripts/stepresize"]
type = "archive"
url = "https://github.com/nclarius/KWin-window-geometry-scripts/archive/refs/tags/step-resize_v2.0.tar.gz"
exact = true
include = ["*/step-resize/**"]
stripcomponents = 2

[".local/share/kwin/scripts/swapsides"]
type = "archive"
url = "https://github.com/nclarius/KWin-window-geometry-scripts/archive/refs/tags/swap-sides_v5.0.tar.gz"
exact = true
include = ["*/swap-sides/**"]
stripcomponents = 2

[".local/share/kwin/scripts/tilegaps"]
type = "archive"
url = "https://github.com/nclarius/tile-gaps/archive/refs/tags/window-gaps_v8.0.tar.gz"
exact = true
stripcomponents = 1
