console_title_template = '{{ .UserName }}@{{ .HostName | splitList "." | first }}:{{ .PWD }}'
pwd = 'osc7'
version = 3
final_space = true

[palette]
  aws = '#ff9900'
  azure = '#008ad7'
  bg = '#282c34'
  blue = '#61afef'
  cyan = '#56b6c2'
  docker = '#1d63ed'
  fg = '#abb2bf'
  golang = '#01acd8'
  google = '#0f9d58'
  gray = '#323842'
  green = '#98c379'
  julia = '#9558b2'
  k8s = '#326ce5'
  magenta = '#c678dd'
  neovim = '#5fb950'
  nix = '#7ebae4'
  nodejs = '#44883e'
  python = '#ffdf76'
  red = '#e06c75'
  rust = '#e33b26'
  tf = '#844fba'
  yellow = '#e5c07b'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'p:blue'
    type = 'path'

    [blocks.segments.properties]
      cache_duration = 'none'
      edge_format = '<b>%s</b>'
      folder_format = '%s'
      folder_icon = '<p:fg>...</>'
      folder_separator_icon = '/'
      max_depth = 4
      style = 'agnoster_short'

  [[blocks.segments]]
    template = " on <p:green>{{ .HEAD }}</>{{ if gt .Behind 0 }} <{{ .Behind }}{{ end }}{{ if gt .Ahead 0 }} >{{ .Ahead }}{{ end }}{{ if gt .StashCount 0 }} *{{ .StashCount }}{{ end }}{{/* we don't check git status, so we never know the number of staged files */}} <p:yellow>-</>"
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      branch_max_length = 32
      cache_duration = 'none'
      commit_icon = '@'
      tag_icon = '#'
      truncate_symbol = '<7>...</>'

  [[blocks.segments]]
    template = '{{ if .Version }} <p:cyan>pkg {{ .Version }}</>{{ end }}'
    type = 'project'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if .Full }} <p:nodejs>node {{ .Full }}</>{{ end }}'
    type = 'node'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if .Venv }} <p:python>py {{ .Venv }}</>{{ else }} <221>py {{ .Full }}{{ end }}'
    type = 'python'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_default = false
      display_mode = 'context'

  [[blocks.segments]]
    template = ' <p:golang>go {{ .Full }}'
    type = 'golang'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <p:rust>rust {{ .Full }}'
    type = 'rust'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if .Root }} as <b><p:yellow>{{ .UserName}}@{{ .HostName | splitList "." | first }}</></>{{ else if .SSHSession }} as <p:yellow>{{ .UserName}}@{{ .HostName | splitList "." | first }}</>{{ end }}'
    type = 'session'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <p:docker>docker {{ .Context }}'
    type = 'docker'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <p:google>gcp {{ .Account }}@{{ .Project }}:{{ .Region }}'
    type = 'gcp'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <p:azure>azure {{ .Name }}'
    type = 'azure'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <p:aws>aws {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}'
    type = 'aws'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if and .Error (contains "|" .String) }}{{ if eq .Code 0 }} <p:green>ok{{ else }} <p:red>err{{ end }} {{ .String }}</>{{ end }}'
    type = 'status'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <p:gray>after {{ .FormattedMs }}</>'
    type = 'executiontime'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'round'
      threshold = 3000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ if gt .Code 0 }}<p:red>></>{{ else }}<p:green>></>{{ end }}'
    type = 'status'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
